alias kns="kubens"
alias kx="kubectx"
alias k=kubectl
alias kl="kubectl logs"
alias klf="kubectl logs -f"
alias kg="kubectl get"
alias ke="kubectl edit"
# get
alias kgpod="kubectl get pod"
alias kging="kubectl get ingress"
alias kgsvc="kubectl get service"
alias kgsec="kubectl get secret"
alias kgns="kubectl get ns"
alias kgnod="kubectl get nodes"
alias kgcrd="kubectl get crd"
alias kgsts="kubectl get sts"
# edit
alias keing="kubectl edit ingress"
alias kedep="kubectl edit deployment"
alias kesvc="kubectl edit service"
alias kecrd="kubectl edit crd"
alias kests="kubectl edit sts"
